NUTRITION_IDENTIFIERS = [
    {"identifier": "dietaryEnergyConsumed", "description": "A quantity sample type that measures the amount of energy consumed."},
    {"identifier": "dietaryFatTotal", "description": "A quantity sample type that measures the total amount of fat consumed."},
    {"identifier": "dietaryFatSaturated", "description": "A quantity sample type that measures the amount of saturated fat consumed."},
    {"identifier": "dietaryCholesterol", "description": "A quantity sample type that measures the amount of cholesterol consumed."},
    {"identifier": "dietarySodium", "description": "A quantity sample type that measures the amount of sodium consumed."},
    {"identifier": "dietaryCarbohydrates", "description": "A quantity sample type that measures the amount of carbohydrates consumed."},
    {"identifier": "dietaryFiber", "description": "A quantity sample type that measures the amount of fiber consumed."},
    {"identifier": "dietarySugar", "description": "A quantity sample type that measures the amount of sugar consumed."},
    {"identifier": "dietaryProtein", "description": "A quantity sample type that measures the amount of protein consumed."},
    {"identifier": "dietaryVitaminA", "description": "A quantity sample type that measures the amount of vitamin A consumed."},
    {"identifier": "dietaryVitaminC", "description": "A quantity sample type that measures the amount of vitamin C consumed."},
    {"identifier": "dietaryCalcium", "description": "A quantity sample type that measures the amount of calcium consumed."},
    {"identifier": "dietaryIron", "description": "A quantity sample type that measures the amount of iron consumed."},
    {"identifier": "dietaryWater", "description": "A quantity sample type that measures the amount of water consumed."},
    {"identifier": "dietaryCaffeine", "description": "A quantity sample type that measures the amount of caffeine consumed."},
    {"identifier": "dietaryFolate", "description": "A quantity sample type that measures the amount of folate consumed."},
    {"identifier": "dietaryPotassium", "description": "A quantity sample type that measures the amount of potassium consumed."},
    {"identifier": "dietaryVitaminB12", "description": "A quantity sample type that measures the amount of vitamin B12 consumed."},
    {"identifier": "dietaryVitaminD", "description": "A quantity sample type that measures the amount of vitamin D consumed."},
    {"identifier": "dietaryVitaminE", "description": "A quantity sample type that measures the amount of vitamin E consumed."},
    {"identifier": "dietaryVitaminK", "description": "A quantity sample type that measures the amount of vitamin K consumed."},
    {"identifier": "dietaryZinc", "description": "A quantity sample type that measures the amount of zinc consumed."},
    {"identifier": "dietaryBiotin", "description": "A quantity sample type that measures the amount of biotin consumed."},
    {"identifier": "dietaryNiacin", "description": "A quantity sample type that measures the amount of niacin consumed."},
    {"identifier": "dietaryPantothenicAcid", "description": "A quantity sample type that measures the amount of pantothenic acid consumed."},
    {"identifier": "dietaryPhosphorus", "description": "A quantity sample type that measures the amount of phosphorus consumed."},
    {"identifier": "dietaryIodine", "description": "A quantity sample type that measures the amount of iodine consumed."},
    {"identifier": "dietaryMagnesium", "description": "A quantity sample type that measures the amount of magnesium consumed."},
    {"identifier": "dietaryManganese", "description": "A quantity sample type that measures the amount of manganese consumed."},
    {"identifier": "dietaryMolybdenum", "description": "A quantity sample type that measures the amount of molybdenum consumed."},
    {"identifier": "dietaryRiboflavin", "description": "A quantity sample type that measures the amount of riboflavin consumed."},
    {"identifier": "dietarySelenium", "description": "A quantity sample type that measures the amount of selenium consumed."},
    {"identifier": "dietaryThiamin", "description": "A quantity sample type that measures the amount of thiamin consumed."},
    {"identifier": "dietaryVitaminB6", "description": "A quantity sample type that measures the amount of vitamin B6 consumed."},
    {"identifier": "dietaryCholine", "description": "A quantity sample type that measures the amount of choline consumed."},
    {"identifier": "dietaryCopper", "description": "A quantity sample type that measures the amount of copper consumed."}
]

# Macros that you want returned from the nutrition estimation machine every time
IMPORTANT_MACROS = ["dietaryEnergyConsumed", "dietaryFatTotal", "dietaryProtein"]